server:
  port: 8201
spring:
  application:
    name: lich-eureka-consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: lich-eureka-consumer:8201
  client:
    service-url:
      defaultZone: http://root:123456@192.168.0.107:8888/eureka/
feign:
  hystrix:
    enabled: true
#负载均衡策略
lich-eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

