server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.107:8888/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456
spring:
  cloud:
    inetutils:
      ignored-interfaces: VMwares.*
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.0.*

